# .readthedocs.yaml

# 使用配置文件的版本 2
version: 2

# 定义构建过程
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # 指定你希望使用的 Python 版本

# 告诉 RTD 你的 Sphinx 配置文件在哪里
sphinx:
   configuration: docs/source/conf.py

# 定义需要安装的 Python 依赖
python:
   install:
     # 1. (关键) 安装你自己的项目包，这样 Sphinx 的 autodoc 才能导入它
     - method: pip
       path: .

     # 2. 安装构建文档所需的工具 (指向我们上一步创建的文件)
     - requirements: docs/requirements.txt