#!/bin/csh
#
# Generated by LNB-MDT

# Minimization
setenv GMX_MAXCONSTRWARN -1
# step6.0 - soft-core minimization
gmx_mpi grompp -f minimization.mdp -o minimization.tpr -c system.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm minimization


# Equilibration
gmx_mpi grompp -f equilibration_1.mdp -o equilibration_1.tpr -c minimization.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm equilibration_1

gmx_mpi grompp -f equilibration_2.mdp -o equilibration_2.tpr -c equilibration_1.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm equilibration_2

gmx_mpi grompp -f equilibration_3.mdp -o equilibration_3.tpr -c equilibration_2.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm equilibration_3

gmx_mpi grompp -f equilibration_4.mdp -o equilibration_4.tpr -c equilibration_3.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm equilibration_4

# Production
gmx_mpi grompp -f production.mdp -o production.tpr -c equilibration_4.gro -p system.top -r system.gro -n index.ndx
gmx_mpi mdrun -deffnm production

