# 用来储存常量
ALL_LIPIDS = ["DAPA",
     "DAPC",
     "DAPE",
     "DAPG",
     "DAPS",
     "DBPA",
     "DBPC",
     "DBPE",
     "DBPG",
     "DBPS",
     "DFPA",
     "DFPC",
     "DFPE",
     "DFPG",
     "DFPS",
     "DGPA",
     "DGPC",
     "DGPE",
     "DGPG",
     "DGPS",
     "DHPC",
     "DIPA",
     "DIPC",
     "DIPE",
     "DIPG",
     "DIPS",
     "DLPA",
     "DLPC",
     "DLPE",
     "DLPG",
     "DLPS",
     "DMPC",
     "DNPA",
     "DNPC",
     "DNPE",
     "DNPG",
     "DNPS",
     "DOPA",
     "DOPC",
     "DOPE",
     "DOPG",
     "DOPS",
     "DPPA",
     "DPPC",
     "DPPE",
     "DPPG",
     "DPPS",
     "DRPA",
     "DRPC",
     "DRPE",
     "DRPG",
     "DRPS",
     "DSPC",
     "DTPA",
     "DTPC",
     "DTPE",
     "DTPG",
     "DTPS",
     "DUPE",
     "DUPS",
     "DVPA",
     "DVPC",
     "DVPE",
     "DVPG",
     "DVPS",
     "DXPA",
     "DXPC",
     "DXPE",
     "DXPG",
     "DXPS",
     "DYPA",
     "DYPC",
     "DYPE",
     "DYPG",
     "DYPS",
     "LPPA",
     "LPPC",
     "LPPE",
     "LPPG",
     "LPPS",
     "PAPA",
     "PAPC",
     "PAPE",
     "PAPG",
     "PAPS",
     "PEPC",
     "PGPA",
     "PGPC",
     "PGPE",
     "PGPG",
     "PGPS",
     "PIPA",
     "PIPC",
     "PIPE",
     "PIPG",
     "PIPS",
     "POPA",
     "POPC",
     "POPE",
     "POPG",
     "POPS",
     "PQPE",
     "PQPS",
     "PRPA",
     "PRPC",
     "PRPE",
     "PRPG",
     "PRPS",
     "PUPA",
     "PUPC",
     "PUPE",
     "PUPS",
     "D6PC",
     "PSM",
     "POP5",
     "DDPC",
     "DUPC",
     "DIPC",
     "PDPC",
     "ODPC",
     "DEPC",
     "DHPE",
     "DLPE",
     "DMPE",
     "DSPE",
     "PPCS",
     "CPG",
     "PPG",
     "PPT",
     "DSMG",
     "DSDG",
     "DSSQ",
     "GMO",
     ]

# Glycolipds
GLYCOLIPIDS = [
     "GM1",
     "DGDG",
     "MGDG",
     "SQDG",
     "CER",
     "GCER",
     "DPPI",
     "PI",
     "PI34",
     "CDGDG",
     "CMGDG",
     "CSQDG",
     "CSQDB",
     "PDGDG",
     "PDGDT",
     "PMGDG",
     "PMGDT",
     "PSQDG",
     ]

# Sterols
STEROLS = ['CHOL','CHOL0','CHOL1','CHOL2','CLINC']

ALL_P = [*ALL_LIPIDS, *GLYCOLIPIDS, *STEROLS]
# Lipids
PC_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PC')]
PE_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PE')]
PG_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PG')]
PS_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PS')]
OTHER_LIPIDS = list(set(ALL_LIPIDS) - set(PC_LIPIDS+PE_LIPIDS+PG_LIPIDS+PS_LIPIDS))

lipids = {'PC Lipids': PC_LIPIDS,
          'PE Lipids': PE_LIPIDS,
          'PG Lipids': PG_LIPIDS,
          'PS Lipids': PS_LIPIDS,
          'Other Lipids': OTHER_LIPIDS,
          'Sterol': STEROLS,
          'Glycoipids': GLYCOLIPIDS
          }
