# 用来储存常量
ALL_LIPIDS = ["DAPC",
     "DBPC",
     "DFPC",
     "DGPC",
     "DIPS",
     "DLPC",
     "DNPC",
     "DOPC",
     "DPPC",
     "DRPC",
     "DTPC",
     "DVPC",
     "DXPC",
     "DYPC",
     "LPPC",
     "PAPC",
     "PEPC",
     "PGPC",
     "PIPC",
     "POPC",
     "PRPC",
     "PUPC",

     "DAPE",
     "DBPE",
     "DFPE",
     "DGPE",
     "DIPE",
     "DLPE",
     "DNPE",
     "DOPE",
     "DPPE",
     "DRPE",
     "DTPE",
     "DUPE",
     "DVPE",
     "DXPE",
     "DYPE",
     "LPPE",
     "PAPE",
     "PGPE",
     "PIPE",
     "POPE",
     "PQPE",
     "PRPE",
     "PUPE",

     "DAPG",
     "DBPG",
     "DFPG",
     "DGPG",
     "DIPG",
     "DLPG",
     "DNPG",
     "DOPG",
     "DPPG",
     "DRPG",
     "DTPG",
     "DVPG",
     "DXPG",
     "DYPG",
     "JFPG",
     "JPPG",
     "LPPG",
     "OPPG",
     "PAPG",
     "PGPG",
     "PIPG",
     "POPG",
     "PRPG",

     "DAPS",
     "DBPS",
     "DFPS",
     "DGPS",
     "DIPS",
     "DLPS",
     "DNPS",
     "DOPS",
     "DPPS",
     "DRPS",
     "DTPS",
     "DUPS",
     "DVPS",
     "DXPS",
     "DYPS",
     "LPPS",
     "PAPS"
     "PGPS",
     "PIPS",
     "POPS",
     "PQPS",
     "PRPS",
     "PUPS",     

     
     ]

# Glycolipds
GLYCOLIPIDS = [
     "DBG1",
     "DBG3",
     "DFGG",
     "DFMG",
     "DPG1",
     "DPG3",
     "DPGG",
     "DPGS",
     "DPMG",
     "DPSG",
     "DXG1",
     "DXG3",
     "FPGG",
     "FPMG",
     "FPSG",
     "OPGG",
     "OPMG",
     "OPSG",
     "PNG1",
     "PNG3",
     "XNG1",
     "XNG3"
     ]

# Sterols
STEROLS = ['CHOL']

ALL_P = [*ALL_LIPIDS, *GLYCOLIPIDS, *STEROLS]
# Lipids
PC_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PC')]
PE_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PE')]
PG_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PG')]
PS_LIPIDS = [i for i in ALL_LIPIDS if (i[-2:] == 'PS')]
OTHER_LIPIDS = list(set(ALL_LIPIDS) - set(PC_LIPIDS+PE_LIPIDS+PG_LIPIDS+PS_LIPIDS))

lipids = {'PC Lipids': PC_LIPIDS,
          'PE Lipids': PE_LIPIDS,
          'PG Lipids': PG_LIPIDS,
          'PS Lipids': PS_LIPIDS,
          'Other Lipids': OTHER_LIPIDS,
          'Sterol': STEROLS,
          'Glycoipids': GLYCOLIPIDS
          }
